name: teensy-gfx-arm

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - 'docs/**'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: nicnewdigate/docker-teensy-cmake-macros:0.5
    steps:
      - name: Create Build directory
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          mkdir -p ${{github.workspace}}
          ls ${{github.workspace}}

      - uses: actions/checkout@v2
        with:
          token: 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
          repository: newdigate/teensy-gfx.git
          ref: main

      - uses: actions/checkout@v2
        with:
          token: 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
          repository: PaulStoffregen/cores.git
          path: ${{github.workspace}}/deps/cores
          fetch-depth: 1
          ref: master

      - name: Configure CMake
        run: |
          cd /__w/teensy-gfx/teensy-gfx && mkdir cmake-build && cd cmake-build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE:FILEPATH="/__w/teensy-gfx/teensy-gfx/cmake/toolchains/teensy41.cmake"

      - name: Build
        working-directory: ${{github.workspace}}
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --target teensy_gfx.o --config $BUILD_TYPE