name: teensy-gfx-arm

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - 'docs/**'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: nicnewdigate/docker-teensy-cmake-macros:0.5
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: PaulStoffregen/cores.git
          path: /__w/teensy-gfx/teensy-gfx/deps/cores
          fetch-depth: 1
          ref: master

      - name: Configure CMake
        run: |
          cd /__w/teensy-gfx/teensy-gfx && mkdir cmake-build && cd cmake-build
          cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE:FILEPATH="/__w/teensy-gfx/teensy-gfx/cmake/toolchains/teensy41.cmake"

      - name: Build
        working-directory: /__w/teensy-gfx/teensy-gfx/cmake-build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --target teensy_gfx.o --config $BUILD_TYPE
