name: teensy-gfx-arm

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'examples/**'
      - 'docs/**'
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    container: nicnewdigate/docker-teensy-cmake-macros:0.4
    defaults:
      run:
        working-directory: ${{github.workspace}}
    steps:
      - name: Create Build directory
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: |
          mkdir -p ${{github.workspace}}
          ls ${{github.workspace}}

      - uses: actions/checkout@v2
        with:
          path: ${{github.workspace}}/teensy-gfx

      - uses: actions/checkout@v2
        with:
          repository: PaulStoffregen/cores.git
          path: ${{github.workspace}}/deps/cores
          fetch-depth: 1
          ref: master

      - name: Configure CMake
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{github.workspace}}/teensy-gfx/build
        # Note the current convention is to use the -S and -B options here to specify source
        # and build directories, but this is only available with CMake 3.13 and higher.
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake $GITHUB_WORKSPACE/teensy-gfx -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_TOOLCHAIN_FILE:FILEPATH="cmake/toolchains/teensy41.cmake"

      - name: Build
        working-directory: ${{github.workspace}}/teensy-gfx/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --target teensy_gfx.o --config $BUILD_TYPE